---
title: 'Need help managing your references? "El Zotero" to the rescue!'
description: |
  In the Lands in Between bibliographies, select Zotero as your hero.
author:
  - name: Juan C. Sanchez-Arias
    url: https://www.juansanar.com/
date: 2022-05-11
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## It's 2022! Use a reference manager ffs

The tradition of passing information to one generation another one has allowed us to use knowledge to our advantage (TODO REF). However, successfully achieving this requires the ability to track down the origins of such knowledge and related observations, opinions, etc. by adding small notes about them within our writing (TODO REF) as references or footnotes. In the past, this was done manually of course (and you'll be surprised how many people still follow this ice age practice) and with the development of technology (e.g., personal computers, text processing software, etc), this labour intensive task can be somewhat automated (you still need to gather the information and make sense of it of course, though one day some dystopian AI might do a better job).

Another challenge that accumulating knowledge brings is managing the sheer amount of content. I wrote a small tidbit about the advantages of using a personal knowledge management tool. In this post, I will focus on managing references, specifically, I will try to convince you should use a reference manager for:

- Organizing your information sources (e.g., articles, books chapters, dissertations, newspapers, etc).
- Inserting and formating citations into your text editor of preference (e.g., MS Word, LibreOffice, Google Docs, Zettlr, VS Code).
- Creating and formatting a bibliography.



**So how do we deal with all this information?**
Specialized software such as reference manager are fundamental aids when citing knowledge in our writing, especially within the ivory walls of academia, where we ("we" as the academic collective through history) have created rules and style formats for this purpose, to the point that almost every single scholarly magazine has developed a format that best suites their copyediting and styling.